webapp/readit/blog/urls.py
from django.urls import path, re_path
from . import views

from django.conf import settings
from django.conf.urls.static import static

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='home'),
    re_path(r'^(?P<match>.+)/$', views.blog_dispatcher, name='blog_dispatcher'),
]

webapp/readit/readit/urls.py
from django.contrib import admin
from django.urls import path, include
from blog.views import post_list
from readitcomments.views import comment_thanks

urlpatterns = [
    path('', post_list, name='home'),
    path('blog/', include('blog.urls', namespace='blog')),
    path('tag/', include('readittags.urls', namespace='tag')),
    path('comment_thanks/<int:post_id>/', comment_thanks, name="comment_thanks"),
    path('admin/', admin.site.urls),
]

webapp/readit/blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import gettext_lazy
from readittags.models import Tag
from django.utils.text import slugify
from simple_history.models import HistoricalRecords
from django.urls import reverse_lazy
from blog.services import models as smodel


class BlogModel(models.Model):
    title = models.CharField(
        max_length=200, verbose_name=gettext_lazy('title'))

    slug = models.CharField(
        max_length=200, verbose_name=gettext_lazy('slug'), unique=True)

    updated = models.DateTimeField(
        auto_now=True, verbose_name=gettext_lazy('updated'))

    created = models.DateTimeField(
        auto_now_add=True, verbose_name=gettext_lazy('created'))

    available = models.BooleanField(
        default=True, verbose_name=gettext_lazy('available'))

    author = models.ForeignKey(
        User, verbose_name=gettext_lazy('author'), related_name='%(class)s_author', on_delete=models.SET_DEFAULT,
        default=1, blank=True, editable=False)

    url = models.URLField(null=True)
    history = HistoricalRecords(inherit=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)

        super(BlogModel, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-created']
        abstract = True


class Category(BlogModel):
    parent = models.ForeignKey(
        'self', on_delete=models.CASCADE, related_name='category_parent', verbose_name=gettext_lazy('category_parent'),
        null=True, blank=True)

    def get_absolute_url(self):
        return reverse_lazy('blog:blog_dispatcher', args=[self.url])

    def clean(self):
        smodel.not_self_i_me_parent(self)
        smodel.wrong_hierarchy(self, Category)

    def save(self, *args, **kwargs):
        self.url = smodel.compile_url(self)
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name = gettext_lazy('verbose_category_name')
        verbose_name_plural = gettext_lazy('verbose_category_name_plural')


class Post(BlogModel):
    description = models.TextField(
        verbose_name=gettext_lazy('description'), default='', blank=True)

    short_description = models.TextField(
        verbose_name=gettext_lazy('short_description'), default='', blank=True)

    image = models.ImageField(
        upload_to='images/post/', verbose_name=gettext_lazy('post_image'), null=True, blank=True)

    optimized_image = models.ImageField(
        upload_to='images/post/optimized', verbose_name=gettext_lazy('post_image'), null=True, blank=True)

    thumbnail_image = models.ImageField(
        upload_to='images/post/thumbnail', verbose_name=gettext_lazy('post_image'), null=True, blank=True)

    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, related_name='post_category', verbose_name=gettext_lazy('category'),
        null=True, blank=True)

    tags = models.ManyToManyField(
        Tag, related_name='post_tags', verbose_name=gettext_lazy('tags'), null=True, blank=True)

    def save(self, *args, **kwargs):
        self.url = smodel.compile_url(self)
        super(Post, self).save(*args, **kwargs)

        # if self.image:
        #     task_img_optimize('images/post/optimized', self.id)
        #     task_create_thumbnail('images/post/thumbnail', self.id)

    def get_breadcrumbs(self):
        return smodel.compile_breadcrumbs(self)

    def get_absolute_url(self):
        return reverse_lazy('blog:blog_dispatcher', args=[self.url])

    class Meta:
        verbose_name = gettext_lazy('verbose_post_name')
        verbose_name_plural = gettext_lazy('verbose_post_name_plural')

webapp/readit/blog/services/models.py
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy


def compile_breadcrumbs(obj) -> list:
    """Сборка хлебных крошек"""
    _b = [{'title': obj.title, 'url': obj.get_absolute_url()}]

    if hasattr(obj, 'category'):
        if obj.category:
            obj = obj.category
            _b.append({'title': obj.title, 'url': obj.get_absolute_url()})

    if hasattr(obj, 'parent'):
        while obj.parent:
            obj = obj.parent
            _b.append({'title': obj.title, 'url': obj.get_absolute_url()})

    return _b[::-1]


def compile_url(obj) -> list:
    """Сборка урла страница, подкатегории, категория"""
    _p = [obj.slug]

    if hasattr(obj, 'category'):
        if obj.category:
            obj = obj.category

            if obj.slug:
                _p.append(obj.slug)

    if hasattr(obj, 'parent'):
        while obj.parent:
            obj = obj.parent
            _p.append(obj.slug)

    return '/'.join(_p[::-1])


def not_self_i_me_parent(obj) -> Exception:
    """Категория неможет быть сама себе родителем"""
    if obj.parent and obj.parent.id == obj.id:
        raise ValidationError({'parent': gettext_lazy('A category cannot refer to self.')})

    return None


def wrong_hierarchy(obj, model) -> Exception:
    """Дочерние категории немогут быть родителями предков"""
    if obj.parent:
        _parent = obj.parent

        while _parent:
            category = model.objects.get(id=_parent.id)

            if category.parent:
                if category.parent.id == obj.id:
                    raise ValidationError({'parent': gettext_lazy('The wrong hierarchy.')})
                else:
                    _parent = category.parent
            else:
                break
    return None

webapp/readit/blog/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404
from django.http import HttpResponseNotFound, HttpResponse, HttpResponseRedirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Post, Category


def blog_dispatcher(request, match):
    if match and Post.objects.filter(url=match).first():
        post = get_object_or_404(Post, url=match)
        return render(request, 'blog/post/post_detail.html', context={'post': post, 'request': request})

    if match and Category.objects.filter(url=match).first():
        context = post_list(request, match)
        return render(request, 'blog/post/post_list.html', context)

    return render(request, 'blog/404.html', status=404)


def post_list(request, match=None):
    if not match:
        posts = get_list_or_404(Post.objects.all())
    else:
        posts = Post.objects.filter(category__url=match)

    if not posts:
        return None

    paginator = Paginator(posts, 9, 3)

    page = request.GET.get('page')

    try:
        page_obj = paginator.page(page)
    except PageNotAnInteger:
        page_obj = paginator.page(1)
    except EmptyPage:
        page_obj = paginator.page(paginator.num_pages)

    context = {'page_obj': page_obj, 'paginator': paginator}

    if match:
        return context

    return render(request, 'blog/post/post_list.html', context)

webapp/readit/blog/templates/blog/post/post_detail.html
{% extends "base.html" %}

{% load static %}
{% load readittags %}
{% load comments %}
{% load categories_menu %}

{% block herowrap %}
    <div class="row no-gutters slider-text js-fullheight align-items-end justify-content-center">
        <div class="col-md-9 ftco-animate pb-5 text-center">
            <h1 class="mb-3 bread">{{ post.title }}</h1>
            <p class="breadcrumbs">
                <span class="mr-2">
                    <a href="{% url "blog:home" %}">Home<i class="ion-ios-arrow-forward ml-2"></i></a>
                </span>

                {% for part in post.get_breadcrumbs %}
                    {% if forloop.last %}
                        <span>{{ part.title|capfirst }}</span>
                    {% else %}
                        <span class="mr-2">
                            <a href="{{ part.url }}">{{ part.title }}<i class="ion-ios-arrow-forward ml-2"></i></a>
                        </span>
                    {% endif %}
                {% endfor %}
            </p>
        </div>
    </div>
{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="{% static "ckeditor5/css/content-styles.css" %}">
{% endblock %}

{% block content %}
    <section class="ftco-section ftco-degree-bg">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 ftco-animate">
                    <p class="mb-5">
                        {% if image %}
                            <img src="{{ post.image.url }}" alt="{{ post.title }}" class="img-fluid">
                        {% endif %}
                    </p>
                    <div class="ck-content">
                        {{ post.description|safe }}
                    </div>
                    <div class="tag-widget post-tag-container mb-5 mt-5">
                        <div class="tagcloud">
                            {% for tag in post.tags.all %}
                                <a href="{{ tag.get_absolute_url }}" class="tag-cloud-link">{{ tag.name }}</a>
                            {% endfor %}
                        </div>
                    </div>

                    <div class="about-author d-flex p-4 bg-light">
                        <div class="bio mr-5">
                            <img src="{% static "blog/images/person_1.jpg" %}" alt="Image placeholder"
                                 class="img-fluid mb-4">
                        </div>
                        <div class="desc">
                            <h3>George Washington</h3>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus itaque, autem
                                necessitatibus voluptate quod mollitia delectus aut, sunt placeat nam vero culpa
                                sapiente consectetur similique, inventore eos fugit cupiditate numquam!</p>
                        </div>
                    </div>

                    <div class="pt-5 mt-5">
                        {% comments post.id %}
                        {% form_comments request post.id %}
                    </div>

                </div> <!-- .col-md-8 -->
                <div class="col-lg-4 sidebar pl-lg-5 ftco-animate">
                    <div class="sidebar-box">
                        <form action="#" class="search-form">
                            <div class="form-group">
                                <span class="icon icon-search"></span>
                                <input type="text" class="form-control" placeholder="Type a keyword and hit enter">
                            </div>
                        </form>
                    </div>
                    <div class="sidebar-box ftco-animate">
                        {% categories_menu %}
                    </div>

                    <div class="sidebar-box ftco-animate">
                        <h3>Recent Blog</h3>
                        <div class="block-21 mb-4 d-flex">
                            <a class="blog-img mr-4"
                               style="background-image: url({% static "blog/images/image_1.jpg" %});"></a>
                            <div class="text">
                                <h3 class="heading"><a href="#">Even the all-powerful Pointing has no control about the
                                    blind texts</a></h3>
                                <div class="meta">
                                    <div><a href="#"><span class="icon-calendar"></span> Nov. 14, 2019</a></div>
                                    <div><a href="#"><span class="icon-person"></span> Admin</a></div>
                                    <div><a href="#"><span class="icon-chat"></span> 19</a></div>
                                </div>
                            </div>
                        </div>
                        <div class="block-21 mb-4 d-flex">
                            <a class="blog-img mr-4"
                               style="background-image: url({% static "blog/images/image_2.jpg" %});"></a>
                            <div class="text">
                                <h3 class="heading"><a href="#">Even the all-powerful Pointing has no control about the
                                    blind texts</a></h3>
                                <div class="meta">
                                    <div><a href="#"><span class="icon-calendar"></span> Nov. 14, 2019</a></div>
                                    <div><a href="#"><span class="icon-person"></span> Admin</a></div>
                                    <div><a href="#"><span class="icon-chat"></span> 19</a></div>
                                </div>
                            </div>
                        </div>
                        <div class="block-21 mb-4 d-flex">
                            <a class="blog-img mr-4"
                               style="background-image: url({% static "blog/images/image_3.jpg" %});"></a>
                            <div class="text">
                                <h3 class="heading"><a href="#">Even the all-powerful Pointing has no control about the
                                    blind texts</a></h3>
                                <div class="meta">
                                    <div><a href="#"><span class="icon-calendar"></span> Nov. 14, 2019</a></div>
                                    <div><a href="#"><span class="icon-person"></span> Admin</a></div>
                                    <div><a href="#"><span class="icon-chat"></span> 19</a></div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="sidebar-box ftco-animate">
                        {% tags_cloud %}
                    </div>

                    <div class="sidebar-box ftco-animate">
                        <h3>Paragraph</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus itaque, autem
                            necessitatibus voluptate quod mollitia delectus aut, sunt placeat nam vero culpa sapiente
                            consectetur similique, inventore eos fugit cupiditate numquam!</p>
                    </div>
                </div>

            </div>
        </div>
    </section> <!-- .section -->
{% endblock %}

{% block scripts %}
    <script>
        $('body').on('click', '.reply', function () {
            console.log($(this).data("id"));
            message_reply.value = $(this).data("id");
        });
    </script>
{% endblock %}

webapp/readit/blog/templates/blog/post/post_list.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <section class="ftco-section bg-light">
        <div class="container">
            <div class="row d-flex">
                {% for post in page_obj %}
                    <div class="col-md-4 d-flex ftco-animate">
                        <div class="blog-entry justify-content-end">
                            <a href="{{ post.get_absolute_url }}" class="block-20"
                               style="background-image: url(
                                       {% if post.image %}{{ post.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %});">
                            </a>
                            <div class="text p-4 float-right d-block">
                                <div class="topper d-flex align-items-center">
                                    <div class="one py-2 pl-3 pr-1 align-self-stretch">
                                        <span class="day">{{ post.created|date:"d" }}</span>
                                    </div>
                                    <div class="two pl-0 pr-3 py-2 align-self-stretch">
                                        <span class="yr">{{ post.created|date:"Y" }}</span>
                                        <span class="mos">{{ post.created|date:"F" }}</span>
                                    </div>
                                </div>
                                <h3 class="heading mb-3">
                                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                                </h3>
                                {% if post.short_description %}
                                    <p>{{ post.short_description|safe|truncatewords:15|linebreaks }}</p>
                                {% endif %}
                                <p>
                                    <a href="{{ post.get_absolute_url }}" class="btn-custom">
                                        <span class="ion-ios-arrow-round-forward mr-3"></span>
                                        Read more
                                    </a>
                                </p>
                            </div>
                        </div>
                    </div>
                {% empty %}
                    <div>Sorry, no posts in this list.</div>
                {% endfor %}
            </div>
            {% if paginator and paginator.num_pages > 1 %}
                {% include "pagination.html" with pg_page=3 %}
            {% endif %}
        </div>
    </section>
{% endblock %}